#!/usr/bin/awk -f
BEGIN {
	printing = 0 # Have we printed anything?
}

/^[0-9]/ {
	if (!printing) {
		printing = 1 # We will print this line
	} else {
		exit 0 # Processing is over now
	}
	
	print
}

# Print the lines that start with four spaces or those with no characters in them
/^    / { if (printing) print }
/^$/ { if (printing) print }
