#!/bin/sh

PROJ=chktex
VERSION=$1
DIR=files/$PROJ.pkg/$VERSION/
TAG=version-$VERSION
TAGFILE=file:///home/svn/$PROJ/tags/$PROJ/$TAG

if [ -z "$VERSION" ]
then
	echo "No version given."
	exit 1
fi

if [ "$VERSION" = "snapshot" ]
then
	echo "Doing snapshot"
	VERSION=snapshot-`date +%Y.%m.%d`
	TAGFILE=file:///home/svn/$PROJ/trunk/$PROJ
	DIR=files/$PROJ.pkg/snapshot
	rm -f $DIR/*
fi

FILE=$PROJ-$VERSION.tar.gz
BASEDIR=$PROJ-$VERSION/

# Export clean copy of the repository
svn export $TAGFILE $BASEDIR
if [ $? != 0 ]
then
	echo "Error while checking out the version."
	rm -rf $BASEDIR
	exit 1
fi

# Prepare version for release
if [ -f $BASEDIR/autogen.sh ]
then
	pushd $BASEDIR
	./autogen.sh
	popd
fi

# Create tar.gz file
tar cvzf $FILE $BASEDIR
mkdir $DIR
mv $FILE $DIR
rm -rf $BASEDIR

# Sign the tar.gz
echo "Now we GPG sign the release:"
pushd $DIR
gpg --detach --armor --sign $FILE
popd

# Generate ChangeLog
svn log $TAGFILE | utils/gnuify-changelog.pl > $DIR/ChangeLog
