#!/bin/sh

PROJ=chktex

#TODO: Check if everything is committed in $PROJ and site

# Create a dump of the repository for online backup
# bzip2 create very small files
# Best after that is gzip --rsyncable not for size as much as for smaller rsync uploads
echo "Dump source control repository"
svnadmin dump -q /home/svn/$PROJ | bzip2 -9 > files/svn/$PROJ.svn-dump.bz2

# Make new site
echo "Update site with new release"
cd site && svn up && make -s
if [ $? != 0 ];
then
	echo "Error while making site"
	exit 1
fi
